# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170820_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('time_sensitive', models.BooleanField()),
                ('approved', models.BooleanField()),
            ],
        ),
    ]
